### ISSUE TITLE
Fix underlined title

### ISSUE THREAD

**Issue by farishan** [Kempongan/does-next-app#33]
Current behaviour:
Ada additional height yang tidak perlu

Expected:
Height sesuai yang dibutuhkan aja supaya gampang layouting sesuai Figma

**Comment by rahmandihamzah** [comment]
@farishan ini fix nya apa aja mas?

**Comment by farishan** [comment]
Sebelum fixing: https://github.com/Kempongan/does-next-app/blob/9ac9639e57b8ea5bf213d7199931c68bcc1fd2d5/components/UnderlinedTitle.js

Setelah fixing: https://github.com/Kempongan/does-next-app/blob/46628cb420f2dc66b8ff43ab3814c92d6e1a934a/components/UnderlinedTitle.js

- Unnecessary height. Ini bikin unexpected spacing + susah pixel perfect karena harus ngitung
- Underline tak ganti border supaya ga perlu render `div` baru
- Tak tambahi microanimation, interaction state (hover), sama custom size props supaya lebih reusable

@rahmandihamzah

**Comment by rahmandihamzah** [comment]
Sip mas @farishan, makasih fix nya.
Yang unexpected spacing ke miss pas develop, di issue ini udah ke fix, tapi perlu ada fix lagi karna ada expected design yg jadi nya gak kehandle

current:
<img width="175" alt="Screen Shot 2021-11-07 at 07 47 34" src="https://user-images.githubusercontent.com/41956897/140628161-da8dd5d9-0b96-4bfb-a3de-501c7c56bdb2.png">

expected:
<img width="183" alt="Screen Shot 2021-11-07 at 07 48 41" src="https://user-images.githubusercontent.com/41956897/140628174-c3a2ae8d-8bff-45e5-a9ce-ba6d508ccb67.png">
